apiVersion: v1
kind: Job
metadata:
  name: cat-facts
spec:
  replicas: 1
  template:
    metadata:
      name: cat-facts-pod
    spec:
      containers:
      - image: cat-facts
        name: cat-facts
      ports:
      - containerPort: 8080
        protocol: TCP
      restartPolicy: Never